/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package livraria;

import java.sql.*;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Adson
 */
public class Home extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "Adson31072002.";
    private static final String dataConn = "jdbc:mysql://localhost:3306/bookdb";

    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
   

    public Home() {
        initComponents();
        upDateDB();
        updateCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //=================================funcao==================================//
    public void upDateDB() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("select * from livros");

            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("Titulo"), rs.getString("ISBN"), rs.getString("Publisher_Id"), rs.getInt("Price")};
                RecordTable.addRow(o);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    
    private void updateCombo(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("select Publisher_Id from publishers");

            rs = pst.executeQuery();
            
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("Publisher_Id"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    
    }

    //=================================funcao==================================//
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jbtnAdd_Editora = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnAtualizar = new javax.swing.JButton();
        jbtnApagar = new javax.swing.JButton();
        jbtnAdd_Autor = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sistema de Livraria");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Titulo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jtxtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(jtxtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 470, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ISBN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jtxtISBN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(jtxtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 470, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Publisher_Id");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Price");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jtxtPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(jtxtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 470, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "ISBN", "Publisher_Id", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 640, 370));

        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 680, 610));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAdd_Editora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAdd_Editora.setText("Adicionar Editora");
        jbtnAdd_Editora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdd_EditoraActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAdd_Editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 40));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnExit.setText("Fechar");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 40));

        jbtnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAtualizar.setText("Atualizar");
        jbtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 40));

        jbtnApagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnApagar.setText("Apagar");
        jbtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApagarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 40));

        jbtnAdd_Autor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAdd_Autor.setText("Adicionar Autor");
        jbtnAdd_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdd_AutorActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAdd_Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, 40));

        jbtnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 40));

        jbtnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAdd.setText("Adicionar Livro");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        jtxtTitulo.setText("");
        jtxtISBN.setText("");
        jtxtPrice.setText("");
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            if(jtxtISBN.getText().isEmpty() || jtxtTitulo.getText().isEmpty() || jtxtPrice.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this, "do the thing");
                
            }
            else if (jtxtISBN.getText().isEmpty() || jtxtTitulo.getText().isEmpty() ){
            
                JOptionPane.showMessageDialog(this, "do the thing");
            }
            else if (jtxtISBN.getText().isEmpty() || jtxtPrice.getText().isEmpty() ){
            
                JOptionPane.showMessageDialog(this, "do the thing");
            }
            else if (jtxtTitulo.getText().isEmpty() || jtxtPrice.getText().isEmpty() ){
            
                JOptionPane.showMessageDialog(this, "do the thing");
            }
            else if (jtxtISBN.getText().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "do the thing");
            }
            else if (jtxtTitulo.getText().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "do the thing");
            }
            else if (jtxtPrice.getText().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "do the thing");
            }
            
            else {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username, password);
                pst = sqlConn.prepareStatement("INSERT INTO livros (Titulo, ISBN, Publisher_Id, Price) value (?, ?, ?, ?)");
                
                pst.setString(1, jtxtTitulo.getText());
                pst.setString(2, jtxtISBN.getText());
                pst.setString(3, (String) jComboBox1.getSelectedItem());
                pst.setString(4, jtxtPrice.getText());
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Adicionado");
                upDateDB();
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtualizarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);

            String titulo = jtxtTitulo.getText();
            String isbn = jtxtISBN.getText();
            String editora = (String) jComboBox1.getSelectedItem();
            String price = jtxtPrice.getText();

            pst = sqlConn.prepareStatement("UPDATE livros SET Titulo= ?, ISBN= ? , Publisher_Id= ?, Price= ? WHERE (ISBN = " + isbn + " )");

            pst.setString(1, titulo);
            pst.setString(2, isbn);
            pst.setString(3, editora);
            pst.setString(4, price);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Atualizado");
            upDateDB();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
    }//GEN-LAST:event_jbtnAtualizarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();

        jtxtTitulo.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        jtxtISBN.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jComboBox1.setSelectedItem(RecordTable.getValueAt(SelectedRows, 2).toString());
        jtxtPrice.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApagarActionPerformed
        // TODO add your handling code here:
        try {

            String isbn = jtxtISBN.getText();

            deleteItem = JOptionPane.showConfirmDialog(null, "deseja apagar este livro ?", "Warning", JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION) {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username, password);
                pst = sqlConn.prepareStatement("delete from livros where ISBN = ?");
                pst.setString(1, isbn);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Livro Removido");
                upDateDB();

                jtxtTitulo.setText("");
                jtxtISBN.setText("");
                jtxtISBN.requestFocus();
                jtxtPrice.setText("");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_jbtnApagarActionPerformed

    private void jbtnAdd_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdd_AutorActionPerformed
        // TODO add your handling code here:
        Autor autor = new Autor();
        this.dispose();
        autor.setVisible(true);

    }//GEN-LAST:event_jbtnAdd_AutorActionPerformed

    private void jbtnAdd_EditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdd_EditoraActionPerformed
        // TODO add your handling code here:
        Editora editora = new Editora();
        this.dispose();
        editora.setVisible(true);
    }//GEN-LAST:event_jbtnAdd_EditoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnAdd_Autor;
    private javax.swing.JButton jbtnAdd_Editora;
    private javax.swing.JButton jbtnApagar;
    private javax.swing.JButton jbtnAtualizar;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JTextField jtxtISBN;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtTitulo;
    // End of variables declaration//GEN-END:variables

    private void If(int showConfirmDialog) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
